WIP Add functional front-end testing
in-toto/layout-web-tool pull request #50
Opened 2020-09-16 10:45 UTC by IshaDave

Purpose:
Testing various features of the web app layout-web-tool using Selenium Webdriver and Flask-testing.

2020-09-16 11:01 UTC, IshaDave commented
A couple things:

1. There are some .vs files that got included into the PR and I'm not sure if you need them (they are meant for only for some Visual Studio functionality right?). Once that is confirmed, I will remove them.
2. There is a 'test database' that is supposed to be specified and I'm not quite sure what that means for in-toto, so I have commented out the function that uses it.

2020-09-25 15:32 UTC, SantiagoTorres requested changes
Pretty cool! 

![selenium](https://user-images.githubusercontent.com/3579933/94286255-c0fd0600-ff22-11ea-8bf9-897ff9a6cacd.gif)
I think we need a couple of minor tweaks before merging...

2020-09-25 15:32 UTC, SantiagoTorres commented on .vs/ProjectSettings.json
> +}
I think all of the .vs files shouldn't be checked in, as they are configuration settings from your editor. You probably want to add
```
.vs/*
```
to our gitignore so we don't add it in further commits. For now you want to remove these files from the commit and update the pr...

2020-09-25 15:32 UTC, SantiagoTorres commented on tests/selenium_testing.py
> +    unittest.main()
In order for this to work, you need to add these requirements to `requirements.txt`

```
diff --git a/requirements.txt b/requirements.txt
index f23a780..26d84e5 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -2,3 +2,5 @@ Flask==1.1.2
 Flask-PyMongo==2.3.0
 Flask-WTF==0.14.3
 in-toto==0.5.0
+Flask-Testing
+selenium
```

2020-09-29 08:44 UTC, IshaDave commented
Thanks for the review! I have made the changes and everything should work now. Two more things:
1. Should I be rebasing the *selenium-testing file* and *updating gitignore and requirements.txt* into two commits for better history?
2. Should I keep adding tests or should it be a separate PR?

2020-09-29 09:10 UTC, lukpueh commented
> Thanks for the review! I have made the changes and everything should work now. Two more things:
> 
> 1. Should I be rebasing the _selenium-testing file_ and _updating gitignore and requirements.txt_ into two commits for better history?

IMO you can squash all 3 commits into one and add a nice description of your addition.

> 2. Should I keep adding tests or should it be a separate PR?

I'm fine either way. IIUC the PR doesn't test anything yet, right? Maybe you can add one initial basic test case to demonstrate how selenium works.

2020-09-29 09:13 UTC, lukpueh reviewed
Very cool stuff, @IshaDave! Apart from two minor nits inline this looks good to go. 

It would also be nice to have a bit more code documentation, or an exemplary test case to make it easier for someone who wants to add tests. What do you think?

2020-09-29 09:13 UTC, lukpueh commented on tests/selenium_testing.py
> +  Setting up Functional testing for layout web tool.
```suggestion
  Setting up functional testing for layout web tool.
```

2020-09-29 09:13 UTC, lukpueh commented on tests/selenium_testing.py
> +  def test_Start(self):
```suggestion
  def test_start(self):
```

2020-09-29 09:31 UTC, IshaDave commented
> IMO you can squash all 3 commits into one and add a nice description of your addition.
Will do!
> IIUC the PR doesn't test anything yet, right?
So a primary test that @SantiagoTorres and I had discussed was to see if the website opened and return a screenshot of the page, then check if you can proceed to the next and come back to this page, then return another screenshot. If the two screenshots are the same, the test runs successfully. I might have misunderstood that part of the instruction, but I am not able to find a way out to compare those two screenshots.

2021-03-03 04:18 UTC, adityasaky commented
@SantiagoTorres indicated this PR is ready for to be merged, @IshaDave. Could I ask you to squash some commits before we proceed? :smile:

2021-03-03 08:44 UTC, IshaDave commented
> @SantiagoTorres indicated this PR is ready for to be merged, @IshaDave. Could I ask you to squash some commits before we proceed? 😄

Sounds great and will do!

2021-04-26 12:28 UTC, adityasaky commented
Thanks for the squashes, @IshaDave!

2021-04-26 12:28 UTC, merged